/*
 * Bipedal Robot Balance Controller with BNO055 IMU
 * Active balance control using BNO055 Euler angles + PID
 * Auto-generated by RobotLearning application
 *
 * Servo API: pServo->Move(angle)  (0-180, center=90)
 * BNO055 API: pBNO->getEulers(double* pPitch, double* pRoll) -> bool (false=ok, true=error)
 *
 * TUNING GUIDE:
 *  1. Start with balanceStand() - hold the robot and watch pitch/roll output
 *  2. If pitch shows constant offset, adjust COM_FORWARD_LEAN_DEG
 *  3. If robot oscillates, reduce PITCH_KP_ANKLE
 *  4. If robot drifts slowly, increase PITCH_KI_ANKLE slightly
 *  5. Once standing is stable, try balanceWeightShiftTest()
 *  6. If it falls sideways during shift, increase ROLL_KP_TURN
 *  7. Once weight shift works, try balanceWalk()
 *  8. If steps too large, reduce WALK_HIP_AMPLITUDE
 *  9. If it falls during foot lift, increase WALK_WEIGHT_SHIFT_MS
 */

#include <cstdio>
#include <cstdint>
#include <cmath>
#include <unistd.h>
#include <signal.h>
#include <sys/time.h>

 // ============================================================
 // HARDWARE INTEGRATION
 // ============================================================

#include "servo.h"
#include "bno.h"

extern Servo* pRightFootServo;
extern Servo* pRightKneeServo;
extern Servo* pRightHipServo;

extern Servo* pLeftFootServo;
extern Servo* pLeftKneeServo;
extern Servo* pLeftHipServo;
extern BNO* pBNO;

// ============================================================
// TUNABLE PARAMETERS - Adjust these for your robot
// ============================================================

// -- IMU Configuration --
const int    CONTROL_LOOP_US = 10000; // 10ms = 100Hz control loop
const int    MIN_LOOP_MS = 8;     // Minimum loop time (ms)
const double RATE_FILTER_ALPHA = 0.2;  // Low-pass on computed pitch/roll rate (0=max filter, 1=no filter)

// -- Servo Configuration --
const int SERVO_MIN = 0;
const int SERVO_MAX = 180;
const int SERVO_CENTER = 90;

// -- Servo Direction Signs --
// Confirmed by manual servo direction test:
//   Hip pitch +15  -> lower leg swings FORWARD      -> DIR = +1
//   Knee      -20  -> lower leg/foot swings BACKWARD (lifts foot) -> DIR = -1 so positive gait = lift
//   Ankle roll +10 -> body leans RIGHT               -> DIR = +1
const int DIR_RIGHT_HIP = 1;   // +1: positive = leg forward; both hips same sign for pitch balance
const int DIR_RIGHT_KNEE = -1;   // -1: positive gait value -> servo below 90 -> lower leg back -> foot lifts
const int DIR_RIGHT_FOOT = 1;   // +1: positive = leans RIGHT; ankle roll for lateral balance
const int DIR_LEFT_HIP = 1;   // +1: positive = leg forward
const int DIR_LEFT_KNEE = -1;   // -1: positive gait value -> servo below 90 -> foot lifts
const int DIR_LEFT_FOOT = 1;   // +1: positive = leans RIGHT; both feet same sign

// -- Balance Gains --
// NEW DESIGN: ankle roll -> lateral (roll) balance; hip pitch -> forward/back (pitch) balance.
// Predictive deadband strategy: let natural damping handle gentle oscillations,
//   correct early only when predicted state exits deadband (velocity-aware).

// Lateral (roll) balance via ankle roll - both feet same direction
const double ROLL_KP_ANKLE = 0.5;   // Ankle roll P gain (positive correction = lean right)
const double ROLL_DEADBAND_DEG = 1.0;  // Tighter deadband for roll (lean bias is persistent)
const double LOOK_AHEAD_SEC = 0.05;  // Predict 50ms ahead for velocity-aware deadband

// Forward/backward (pitch) balance via hip pitch - both hips same direction
// positive hipCorrection = both hips forward = body shifts backward = corrects forward lean
const double PITCH_KP_HIP = 0.4;   // Hip pitch P gain (used by balanceStand)
const double DEADBAND_DEG = 2.0;   // Pitch deadband threshold (used by balanceStand)

// Walk-specific pitch control — gains tuned for BNO055 (fast IMU, ~0.1s response)
// BNO055 is ~7x faster than MPU6050 was — old gains of KP=2.0 cause immediate oscillation.
// D-term disabled: differenced pitchRate has large spikes (1 deg / 10ms = 100 deg/s).
const double WALK_PITCH_KP = 0.4;   // Walk: proportional gain (tuned: 0.5 oscillates, 0.3 too weak)
const double WALK_PITCH_KI = 0.1;   // Walk: integral gain — eliminates persistent pitch bias
const double WALK_PITCH_KI_MAX = 10.0;  // Walk: anti-windup clamp on integral accumulator (deg·s)
const double WALK_PITCH_KD = 0.0;   // Walk: derivative disabled (differenced rate too noisy)
const double WALK_ROLL_KP = 0.3;   // Walk: roll correction gain during SETTLE phases (ankle differential; 0.3 confirmed best)
const double WALK_DEADBAND = 1.0;   // Walk: deadband (wider to avoid fighting small natural tilts)
const double WALK_HIP_LIMIT = 40.0;  // Walk: max hip correction
const double WALK_LOOK_AHEAD = 0.0;   // Walk: no look-ahead — differenced pitchRate is too noisy for prediction

// -- myWalkSmooth parameters (push-off walk with hip/knee compensation) --
// 4-phase design: SHIFT overlaps with hip return from previous PUSH,
// keeping support ankle planted until weight fully transfers.
const double MWS_SHIFT_MS = 450.0;  // Weight-shift + hip-return phase (ms); needs to be long enough for both
const double MWS_PUSH_MS = 450.0;  // Hip push phase (ms)
const double MWS_ANKLE_TILT = 18.0;   // Support ankle tilt (deg)
const double MWS_ANKLE_PUSH = 30.0;   // Lift ankle push (deg)
const double MWS_HIP_PUSH = 30.0;   // Hip push forward (deg)
const double MWS_KNEE_COMP = 30.0;   // Knee compensation (deg; equal to hip push keeps torso vertical)
const double MWS_PITCH_KP = 0.5;    // Pitch P gain for myWalkSmooth (separate from walkSmooth's 0.4 — push-off dynamics differ)

// -- Servo Rate Limiter (for multi-servo gait modes) --
const double MAX_SERVO_RATE_DEG = 3.0;  // Used by rateLimitServo() in walking modes

// -- Center of Mass Compensation --
// Target pitch for balance. 0 = perfectly upright.
// Walking naturally creates 5-10 deg forward pitch - set this to accept that.
const double COM_FORWARD_LEAN_DEG = 3.0;//3.0;   // Target forward lean (deg). Walking naturally pulls body backward during swing — pre-bias forward.

// -- PID Limits --
const double ANKLE_LIMIT_DEG = 15.0;  // Max ankle correction
const double HIP_LIMIT_DEG = 20.0;  // Max hip correction
const double PITCH_INTEGRAL_MAX = 30.0;
const double ROLL_INTEGRAL_MAX = 20.0;

// -- Walking Parameters (legacy balanceWalk) --
// Ankle roll replaces knee bend for weight shift - more direct, no pitch side-effect.
const double WALK_HIP_AMPLITUDE = 20.0;   // Hip swing degrees (user test: 30 worked, 20 conservative)
const double WALK_KNEE_LIFT = 20.0;   // Swing knee lift degrees (positive gait -> DIR=-1 -> servo below 90 -> foot lifts)
const double WALK_ANKLE_SHIFT = 10.0;   // Ankle roll weight shift degrees (user test: 10 holds single-leg balance)
const double WALK_STEP_PERIOD_MS = 2000;   // Step duration ms (conservative start)
const double WALK_WEIGHT_SHIFT_MS = 600.0;  // Time to ramp ankle shift and settle before stepping
const double WALK_TURN_SHIFT = 0.0;    // Turn shift disabled

// -- Smooth phase walk parameters (walkSmooth / testSingleLegSmooth) --
const double SW_SHIFT_MS = 400.0;  // Weight-shift phase (ms): floor ~350 — below that ankle shift is incomplete
const double SW_SWING_MS = 500.0;  // Foot-swing phase (ms): 500 is fine for 9-deg hip arc in air
const double SW_SETTLE_MS = 150.0;  // Post-swing settle (ms): pitch correction handles stabilization, only need ankle-return time
const double SW_TRANS_MS = 600.0;  // Single-leg test transition duration (ms)
const double SW_HOLD_MS = 3000.0; // Single-leg hold duration (ms)
const double SW_KNEE_BASE = 0.0;   // Standing knee angle (0 = straight; increase if robot stands bent-knee)
const double SW_ANKLE_SHIFT = 17.0;  // Right support ankle (right ankle is less effective — needs full 17 deg)
const double SW_ANKLE_SHIFT_L = 11.0;  // Left support ankle (left ankle more effective — 10 gave symmetric roll but insufficient foot clearance; 17 caused heavy left swing)
const double SW_ANKLE_PUSH = 20.0;  // Push ankle (same for both sides; reducing this caused instability)
const double SW_COM_HIP = 0.0;   // Support hip forward for COM advance (0=disabled, was causing forward fall)
const double SW_COM_KNEE = 0.0;   // Support knee bend for COM advance (0=disabled)
const double SW_SWING_HIP = 8.0;   // Swing hip forward (support hip returns during swing, not weight-shift)
const double HIP_R_TRIM = 1.0;   // Right hip mechanical offset (reduced from 3.0 — SW_ANKLE_SHIFT_L now handles symmetry; 3.0 made right arc too large)
const double HIP_L_TRIM = 0.0;   // Left  hip mechanical offset — tune to fix stride asymmetry (positive = more forward)
const double SW_SWING_KNEE = 12.0;  // Left swing knee peak clearance
const double SW_SWING_KNEE_R = 16.0;  // Right swing knee (extra clearance: HIP_R_TRIM makes right foot arc larger)
const double SW_HIP_KNEE_FF = 0.5;   // Support hip feedforward per degree of swing knee lift (counters COM shift)

// -- Safety --
const double MAX_TILT_DEG = 35.0;  // Emergency stop if tilt exceeds this

// ============================================================
// IMU STATE AND PROCESSING
// ============================================================

struct IMUState {
    double pitch;         // Forward/backward tilt (positive = leaning forward)
    double roll;          // Sideways tilt (positive = leaning right)
    double pitchRate;     // Angular velocity (deg/s)
    double rollRate;      // Angular velocity (deg/s)
    double lastUpdateTime;
    bool initialized;
};

IMUState imu = { 0, 0, 0, 0, 0.0, false };
volatile bool balanceRunning = true;

void balanceSignalHandler(int sig) {
    balanceRunning = false;
}

double getTimeSeconds() {
    struct timeval tv;
    gettimeofday(&tv, NULL);
    return tv.tv_sec + tv.tv_usec / 1000000.0;
}

// Read BNO055 Euler angles and compute pitch/roll rates by differencing.
// BNO055 provides stable Euler angles directly — no calibration or filter needed.
// Sign convention: positive pitch = lean forward, positive roll = lean right.
// If BNO055 axes differ from convention, negate pitch/roll assignments below.
void imuUpdate() {
    double rawPitch = 0, rawRoll = 0;
    if (pBNO->getEulers(&rawPitch, &rawRoll)) return;  // returns true = error, false = success

    double newPitch = rawPitch;  // positive = lean forward (confirmed)
    double newRoll = -rawRoll;   // BNO055 roll is inverted: negate to get positive = lean right

    double now = getTimeSeconds();

    if (!imu.initialized) {
        imu.pitch = newPitch;
        imu.roll = newRoll;
        imu.pitchRate = 0;
        imu.rollRate = 0;
        imu.lastUpdateTime = now;
        imu.initialized = true;
        return;
    }

    double dt = now - imu.lastUpdateTime;
    if (dt <= 0 || dt > 0.2) dt = 0.01;
    imu.lastUpdateTime = now;

    // Compute rates by differencing; low-pass to suppress vibration noise.
    double rawPitchRate = (newPitch - imu.pitch) / dt;
    double rawRollRate = (newRoll - imu.roll) / dt;
    imu.pitchRate = RATE_FILTER_ALPHA * rawPitchRate + (1.0 - RATE_FILTER_ALPHA) * imu.pitchRate;
    imu.rollRate = RATE_FILTER_ALPHA * rawRollRate + (1.0 - RATE_FILTER_ALPHA) * imu.rollRate;

    imu.pitch = newPitch;
    imu.roll = newRoll;
}

// Stream BNO055 readings for 10 seconds to verify sensor orientation.
// Tilt robot forward/back to confirm pitch sign; left/right to confirm roll sign.
// If signs are reversed, negate newPitch/newRoll assignments in imuUpdate().
void testIMU() {
    printf("=== BNO055 ORIENTATION TEST (10 seconds) ===\n");
    imu.initialized = false;

    printf("\nVerify axes — tilt the robot and check sign convention:\n");
    printf("  Pitch + = lean FORWARD    Pitch - = lean BACKWARD\n");
    printf("  Roll  + = lean RIGHT      Roll  - = lean LEFT\n\n");

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;

    double startTime = getTimeSeconds();
    double lastPrint = -1.0;

    while (balanceRunning && (getTimeSeconds() - startTime) < 10.0) {
        imuUpdate();
        double elapsed = getTimeSeconds() - startTime;
        if (elapsed - lastPrint >= 0.2) {
            lastPrint = elapsed;
            printf("t=%4.1f  pitch=%6.2f  roll=%6.2f  pitchRate=%6.1f  rollRate=%6.1f\n",
                elapsed, imu.pitch, imu.roll, imu.pitchRate, imu.rollRate);
        }
        usleep(10000);  // 10ms loop
    }
    printf("\nIMU test done.\n");
}


// ============================================================
// BALANCE CONTROLLER
// ============================================================

struct BalanceState {
    double pitchIntegral;
    double rollIntegral;

    // Outputs (degrees offset from center)
    // ankleCorrection: applied to BOTH ankles, same sign -> lateral (roll) balance
    //   positive = both ankles above 90 = body leans RIGHT
    // hipCorrection:   applied to BOTH hips, same sign -> pitch balance
    //   positive = both hips above 90 = legs forward = body shifts backward
    double ankleCorrection;
    double hipCorrection;
};

BalanceState bal = { 0, 0, 0, 0 };

void balanceUpdate(double dt) {
    // --- Roll correction via Ankle Roll (primary lateral corrector) ---
    // Both ankles same direction: positive = lean right. Corrects leftward fall.
    // Predictive deadband: let natural damping handle small swings,
    //   intervene early only when predicted roll exits deadband.
    double predictedRoll = imu.roll + imu.rollRate * LOOK_AHEAD_SEC;
    double predictedRollError = 0.0 - predictedRoll;   // positive = robot leaning left, need to lean right

    if (fabs(predictedRollError) < ROLL_DEADBAND_DEG) {
        bal.ankleCorrection = 0.0;
    }
    else {
        double effRollError = predictedRollError > 0.0
            ? predictedRollError - ROLL_DEADBAND_DEG
            : predictedRollError + ROLL_DEADBAND_DEG;
        bal.ankleCorrection = ROLL_KP_ANKLE * effRollError;
    }
    if (bal.ankleCorrection > ANKLE_LIMIT_DEG) bal.ankleCorrection = ANKLE_LIMIT_DEG;
    if (bal.ankleCorrection < -ANKLE_LIMIT_DEG) bal.ankleCorrection = -ANKLE_LIMIT_DEG;

    // --- Pitch correction via Hip Pitch (primary forward/backward corrector) ---
    // Both hips same direction. With feet fixed:
    //   positive hipCorrection = legs forward = body shifts backward = corrects forward lean.
    // predictedPitchError positive = robot leaning forward = apply positive hip = correct.
    double predictedPitch = imu.pitch + imu.pitchRate * LOOK_AHEAD_SEC;
    double predictedPitchError = predictedPitch - COM_FORWARD_LEAN_DEG;  // + = leaning forward

    if (fabs(predictedPitchError) < DEADBAND_DEG) {
        bal.hipCorrection = 0.0;
        bal.pitchIntegral = 0.0;
    }
    else {
        double effectiveError = predictedPitchError > 0.0
            ? predictedPitchError - DEADBAND_DEG
            : predictedPitchError + DEADBAND_DEG;
        bal.hipCorrection = PITCH_KP_HIP * effectiveError;
    }
    if (bal.hipCorrection > HIP_LIMIT_DEG) bal.hipCorrection = HIP_LIMIT_DEG;
    if (bal.hipCorrection < -HIP_LIMIT_DEG) bal.hipCorrection = -HIP_LIMIT_DEG;

}


// ============================================================
// SERVO COMMAND FUNCTIONS
// ============================================================

int clampServo(int angle) {
    if (angle < SERVO_MIN) return SERVO_MIN;
    if (angle > SERVO_MAX) return SERVO_MAX;
    return angle;
}

// Rate-limit a servo command: don't move more than MAX_SERVO_RATE_DEG per cycle
int rateLimitServo(int target, int current) {
    int diff = target - current;
    int maxStep = (int)MAX_SERVO_RATE_DEG;
    if (maxStep < 1) maxStep = 1;
    if (diff > maxStep)  diff = maxStep;
    if (diff < -maxStep) diff = -maxStep;
    return current + diff;
}

// Apply 6 servos with gait offsets + balance corrections
void applyServoPositions(
    double rHipOff, double rKneeOff, double rFootOff,
    double lHipOff, double lKneeOff, double lFootOff)
{
    double rHip = rHipOff + bal.hipCorrection;
    double rKnee = rKneeOff;
    double rFoot = rFootOff + bal.ankleCorrection;
    double lHip = lHipOff + bal.hipCorrection;
    double lKnee = lKneeOff;
    double lFoot = lFootOff + bal.ankleCorrection;

    // Ankles FIRST for fastest balance response
    pRightFootServo->Move(clampServo(SERVO_CENTER + (int)(rFoot * DIR_RIGHT_FOOT)));
    pLeftFootServo->Move(clampServo(SERVO_CENTER + (int)(lFoot * DIR_LEFT_FOOT)));
    pRightHipServo->Move(clampServo(SERVO_CENTER + (int)(rHip * DIR_RIGHT_HIP)));
    pLeftHipServo->Move(clampServo(SERVO_CENTER + (int)(lHip * DIR_LEFT_HIP)));
    pRightKneeServo->Move(clampServo(SERVO_CENTER + (int)(rKnee * DIR_RIGHT_KNEE)));
    pLeftKneeServo->Move(clampServo(SERVO_CENTER + (int)(lKnee * DIR_LEFT_KNEE)));
}

// Center all servos (no balance)
void centerAllServos() {
    pRightHipServo->Move(SERVO_CENTER);
    pRightKneeServo->Move(SERVO_CENTER);
    pRightFootServo->Move(SERVO_CENTER);
    pLeftHipServo->Move(SERVO_CENTER);
    pLeftKneeServo->Move(SERVO_CENTER);
    pLeftFootServo->Move(SERVO_CENTER);
}


// ============================================================
// SMOOTH INTERPOLATION HELPERS
// ============================================================

// Ease-in + ease-out: velocity is zero at t=0 and t=1 — eliminates snap at phase edges.
static double smoothstep(double t) {
    if (t <= 0) return 0.0; if (t >= 1) return 1.0;
    return t * t * (3.0 - 2.0 * t);
}

// Sine arc: 0 → 1 → 0 over [0,1].
// Use for ankle push (zero at start AND end) and knee swing (natural foot arc).
static double sinArc(double t) {
    if (t <= 0 || t >= 1) return 0.0;
    return sin(t * M_PI);
}

// Move the 6 core servos (hip, knee, ankle × 2).
// All angles in degrees offset from servo center; DIR constants handle physical mounting.
static void setLegs(double rHip, double lHip,
    double rKnee, double lKnee,
    double rAnkle, double lAnkle) {
    pRightHipServo->Move(clampServo(SERVO_CENTER + (int)((rHip + HIP_R_TRIM) * DIR_RIGHT_HIP)));
    pLeftHipServo->Move(clampServo(SERVO_CENTER + (int)((lHip + HIP_L_TRIM) * DIR_LEFT_HIP)));
    pRightKneeServo->Move(clampServo(SERVO_CENTER + (int)(rKnee * DIR_RIGHT_KNEE)));
    pLeftKneeServo->Move(clampServo(SERVO_CENTER + (int)(lKnee * DIR_LEFT_KNEE)));
    pRightFootServo->Move(clampServo(SERVO_CENTER + (int)(rAnkle * DIR_RIGHT_FOOT)));
    pLeftFootServo->Move(clampServo(SERVO_CENTER + (int)(lAnkle * DIR_LEFT_FOOT)));
}


// ============================================================
// WALKING STATE MACHINE
// ============================================================

enum WalkPhase {
    WALK_DOUBLE_SUPPORT,
    WALK_SHIFT_RIGHT,
    WALK_LIFT_LEFT,
    WALK_SWING_LEFT,
    WALK_PLANT_LEFT,
    WALK_SHIFT_LEFT,
    WALK_LIFT_RIGHT,
    WALK_SWING_RIGHT,
    WALK_PLANT_RIGHT
};

const char* walkPhaseNames[] = {
    "DOUBLE_SUPPORT", "SHIFT_RIGHT", "LIFT_LEFT", "SWING_LEFT", "PLANT_LEFT",
    "SHIFT_LEFT", "LIFT_RIGHT", "SWING_RIGHT", "PLANT_RIGHT"
};


// Maintain control loop timing
void controlLoopDelay(double loopStartTime) {
    double elapsed = getTimeSeconds() - loopStartTime;
    int remainUs = CONTROL_LOOP_US - (int)(elapsed * 1000000);
    if (remainUs > 0) usleep(remainUs);
}

// Pad loop to minimum time (prevents D-term feedback from too-fast loops)
void enforceMinLoopTime(double loopStartTime) {
    double elapsed = getTimeSeconds() - loopStartTime;
    int elapsedMs = (int)(elapsed * 1000);
    if (elapsedMs < MIN_LOOP_MS) {
        usleep((MIN_LOOP_MS - elapsedMs) * 1000);
    }
}

// Check safety limits, returns true if safe
bool safetyCheck() {
    if (fabs(imu.pitch) > MAX_TILT_DEG || fabs(imu.roll) > MAX_TILT_DEG) {
        printf("EMERGENCY: Tilt exceeded %.1f deg (pitch=%.1f, roll=%.1f)\n",
            MAX_TILT_DEG, imu.pitch, imu.roll);
        centerAllServos();
        return false;
    }
    return true;
}


// ============================================================
// DIAGNOSTIC: IMU READING TEST (no servo movement)
// ============================================================

void imuDiagnostic() {
    printf("=== IMU DIAGNOSTIC MODE ===\n");
    printf("No servos will move. Just reading and printing IMU data.\n");
    printf("Tilt the robot by hand and verify:\n");
    printf("  - Pitch positive when leaning FORWARD\n");
    printf("  - Pitch negative when leaning BACKWARD\n");
    printf("  - Roll positive when leaning RIGHT\n");
    printf("  - Roll negative when leaning LEFT\n");
    printf("Press Ctrl+C to stop.\n\n");

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;
    imu.initialized = false;

    while (balanceRunning) {
        double loopStart = getTimeSeconds();

        imuUpdate();

        // Print every 200ms (no servo delay, so loop is fast)
        static int printCount = 0;
        if (++printCount >= 20) {
            double pitchErr = imu.pitch - COM_FORWARD_LEAN_DEG;
            double hipWouldBe = pitchErr * PITCH_KP_HIP;
            double rollErr = 0.0 - imu.roll;
            double ankleWouldBe = rollErr * ROLL_KP_ANKLE;
            printf("Pitch:%6.1f PitchErr:%6.1f HipWould:%5.1f | Roll:%6.1f AnkleWould:%5.1f\n",
                imu.pitch, pitchErr, hipWouldBe, imu.roll, ankleWouldBe);
            printCount = 0;
        }

        controlLoopDelay(loopStart);
    }

    printf("IMU diagnostic stopped.\n");
}


// ============================================================
// DIAGNOSTIC: SERVO STEP RESPONSE TEST
// Measures actual servo response time via IMU feedback.
// ============================================================

void servoResponseTest() {
    printf("=== SERVO STEP RESPONSE TEST ===\n");
    printf("This test measures servo transport delay, rise time, and settling time.\n");
    printf("The robot must be standing freely (not held).\n\n");

    const double STEP_ANGLE_DEG = 3.0;    // Step size in degrees (small to avoid falling)
    const double HOLD_TIME_SEC = 3.0;    // How long to hold each position
    const int    MAX_SAMPLES = 3000;    // Max samples to record per phase

    struct Sample {
        double time_ms;
        double pitch;
        double pitchRate;
    };
    Sample* samples = new Sample[MAX_SAMPLES];

    // --- Phase 0: Center servos and let IMU settle ---
    printf("Centering servos and waiting 2s for IMU to settle...\n");
    centerAllServos();
    usleep(500000);

    // Warm up IMU filter
    for (int i = 0; i < 500; i++) {
        imuUpdate();
        usleep(2000);
    }

    double baselinePitch = imu.pitch;
    printf("Baseline pitch: %.2f deg\n\n", baselinePitch);

    // --- Phase 1: Step forward (tilt ankles by STEP_ANGLE_DEG) ---
    printf("--- STEP +%.0f degrees ---\n", STEP_ANGLE_DEG);
    printf("Commanding ankle servos to +%.0f deg from center...\n", STEP_ANGLE_DEG);

    double stepStart = getTimeSeconds();
    int targetR = clampServo(SERVO_CENTER + (int)(STEP_ANGLE_DEG * DIR_RIGHT_FOOT));
    int targetL = clampServo(SERVO_CENTER + (int)(STEP_ANGLE_DEG * DIR_LEFT_FOOT));
    pRightFootServo->Move(targetR);
    pLeftFootServo->Move(targetL);

    // Record IMU at max rate
    int nSamples = 0;
    bool foundStart = false;
    bool foundTarget = false;
    double timeFirstMove = -1;
    double timeReachTarget = -1;
    double timeSettle = -1;
    double peakPitch = baselinePitch;

    while (nSamples < MAX_SAMPLES) {
        imuUpdate();
        double now = getTimeSeconds();
        double elapsed_ms = (now - stepStart) * 1000.0;

        if (elapsed_ms > HOLD_TIME_SEC * 1000.0) break;

        samples[nSamples].time_ms = elapsed_ms;
        samples[nSamples].pitch = imu.pitch;
        samples[nSamples].pitchRate = imu.pitchRate;
        nSamples++;

        double moved = imu.pitch - baselinePitch;

        // Detect first significant movement (>0.5 deg from baseline)
        if (!foundStart && fabs(moved) > 0.5) {
            foundStart = true;
            timeFirstMove = elapsed_ms;
        }

        // Detect reaching target (within 1 deg of target)
        if (!foundTarget && fabs(moved) >= STEP_ANGLE_DEG - 1.0) {
            foundTarget = true;
            timeReachTarget = elapsed_ms;
        }

        // Track peak
        if (fabs(moved) > fabs(peakPitch - baselinePitch)) {
            peakPitch = imu.pitch;
        }

        // No usleep - run as fast as possible to get max time resolution
    }

    // Print summary
    printf("\n--- STEP RESPONSE RESULTS ---\n");
    printf("Samples collected: %d\n", nSamples);
    if (nSamples > 0) {
        printf("Sample rate: %.0f Hz (%.1f ms/sample)\n",
            nSamples / (samples[nSamples - 1].time_ms / 1000.0),
            samples[nSamples - 1].time_ms / nSamples);
    }
    printf("Transport delay (>0.5 deg):  ");
    if (timeFirstMove >= 0) printf("%.1f ms\n", timeFirstMove);
    else printf("NOT DETECTED\n");

    printf("Rise time (to %.0f deg):      ", STEP_ANGLE_DEG - 1.0);
    if (timeReachTarget >= 0) printf("%.1f ms\n", timeReachTarget);
    else printf("NOT REACHED\n");

    printf("Peak pitch:                  %.1f deg (overshoot: %.1f deg)\n",
        peakPitch, peakPitch - baselinePitch - STEP_ANGLE_DEG);

    // Print raw samples (every Nth to keep output manageable)
    int printEvery = nSamples / 100;
    if (printEvery < 1) printEvery = 1;
    printf("\n--- RAW SAMPLES (every %d) ---\n", printEvery);
    printf("Time(ms)  Pitch(deg)  Rate(deg/s)\n");
    for (int i = 0; i < nSamples; i += printEvery) {
        printf("%7.1f   %7.2f     %7.1f\n",
            samples[i].time_ms, samples[i].pitch, samples[i].pitchRate);
    }
    // Always print last sample
    if ((nSamples - 1) % printEvery != 0 && nSamples > 0) {
        printf("%7.1f   %7.2f     %7.1f\n",
            samples[nSamples - 1].time_ms, samples[nSamples - 1].pitch, samples[nSamples - 1].pitchRate);
    }

    // --- Phase 2: Step back to center ---
    printf("\n--- STEP BACK TO CENTER ---\n");
    double returnStart = getTimeSeconds();
    pRightFootServo->Move(SERVO_CENTER);
    pLeftFootServo->Move(SERVO_CENTER);

    int nReturn = 0;
    bool foundReturn = false;
    double timeReturnStart = -1;
    double timeReturnSettle = -1;

    while (nReturn < MAX_SAMPLES) {
        imuUpdate();
        double now = getTimeSeconds();
        double elapsed_ms = (now - returnStart) * 1000.0;

        if (elapsed_ms > HOLD_TIME_SEC * 1000.0) break;

        samples[nReturn].time_ms = elapsed_ms;
        samples[nReturn].pitch = imu.pitch;
        samples[nReturn].pitchRate = imu.pitchRate;
        nReturn++;

        double distFromBaseline = fabs(imu.pitch - baselinePitch);

        if (!foundReturn && distFromBaseline < fabs(peakPitch - baselinePitch) - 0.5) {
            foundReturn = true;
            timeReturnStart = elapsed_ms;
        }
    }

    printf("Return transport delay:  ");
    if (timeReturnStart >= 0) printf("%.1f ms\n", timeReturnStart);
    else printf("NOT DETECTED\n");

    printf("\n--- RETURN SAMPLES (every %d) ---\n", printEvery);
    printf("Time(ms)  Pitch(deg)  Rate(deg/s)\n");
    for (int i = 0; i < nReturn; i += printEvery) {
        printf("%7.1f   %7.2f     %7.1f\n",
            samples[i].time_ms, samples[i].pitch, samples[i].pitchRate);
    }
    if ((nReturn - 1) % printEvery != 0 && nReturn > 0) {
        printf("%7.1f   %7.2f     %7.1f\n",
            samples[nReturn - 1].time_ms, samples[nReturn - 1].pitch, samples[nReturn - 1].pitchRate);
    }

    // Cleanup
    centerAllServos();
    delete[] samples;
    printf("\n=== SERVO RESPONSE TEST COMPLETE ===\n");
}


// ============================================================
// MODE 1: STANDING WITH ACTIVE BALANCE (ankle-only, fast)
// ============================================================

void balanceStand() {
    printf("=== STANDING BALANCE MODE ===\n");
    printf("Lateral : ankle roll  Kp=%.2f deadband=%.1f\n", ROLL_KP_ANKLE, ROLL_DEADBAND_DEG);
    printf("Pitch   : hip pitch   Kp=%.2f deadband=%.1f\n", PITCH_KP_HIP, DEADBAND_DEG);
    printf("Press Ctrl+C to stop.\n\n");

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;
    bal.pitchIntegral = 0;
    bal.rollIntegral = 0;
    imu.initialized = false;

    double lastLoopTime = getTimeSeconds();

    while (balanceRunning) {
        double loopStart = getTimeSeconds();

        imuUpdate();

        double dt = loopStart - lastLoopTime;
        lastLoopTime = loopStart;
        if (dt < 0.002 || dt > 0.2) dt = 0.01;

        balanceUpdate(dt);

        if (!safetyCheck()) break;

        // Ankle roll: both feet same sign -> lateral balance (positive = lean right)
        pRightFootServo->Move(clampServo(SERVO_CENTER + (int)(bal.ankleCorrection * DIR_RIGHT_FOOT)));
        pLeftFootServo->Move(clampServo(SERVO_CENTER + (int)(bal.ankleCorrection * DIR_LEFT_FOOT)));

        // Hip pitch: both hips same sign -> pitch balance (positive = legs fwd = body back)
        pRightHipServo->Move(clampServo(SERVO_CENTER + (int)(bal.hipCorrection * DIR_RIGHT_HIP)));
        pLeftHipServo->Move(clampServo(SERVO_CENTER + (int)(bal.hipCorrection * DIR_LEFT_HIP)));

        // Knees: center
        pRightKneeServo->Move(SERVO_CENTER);
        pLeftKneeServo->Move(SERVO_CENTER);

        static double lastPrint = 0;
        if (loopStart - lastPrint >= 0.5) {
            printf("Pitch:%+5.1f HipCorr:%+5.1f | Roll:%+5.1f AnkleCorr:%+5.1f dt=%.0fms\n",
                imu.pitch, bal.hipCorrection, imu.roll, bal.ankleCorrection, dt * 1000);
            lastPrint = loopStart;
        }

        enforceMinLoopTime(loopStart);
    }

    centerAllServos();
    printf("Standing balance stopped.\n");
}


// ============================================================
// MODE 1b: SINGLE LEG STAND TEST
// ============================================================
// Tests if the robot can balance on one foot.
// This MUST work before walking can work.

void singleLegStandTest() {
    printf("=== SINGLE LEG STAND TEST ===\n");
    printf("Phase 1: Shift weight onto right foot (3 sec)\n");
    printf("Phase 2: Lift left foot slightly (hold 5 sec)\n");
    printf("Phase 3: Lower left foot, recenter (2 sec)\n");
    printf("Phase 4: Shift weight onto left foot (3 sec)\n");
    printf("Phase 5: Lift right foot slightly (hold 5 sec)\n");
    printf("Phase 6: Lower right foot, recenter (2 sec)\n");
    printf("Press Ctrl+C to stop.\n\n");

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;
    bal.pitchIntegral = 0;
    bal.rollIntegral = 0;
    imu.initialized = false;

    double startTime = getTimeSeconds();
    double lastLoopTime = startTime;
    int gaitServoIndex = 0;
    int currentPhase = 0;
    double phaseStartTime = startTime;

    // Phase durations in seconds
    double phaseDurations[] = { 3.0, 5.0, 2.0, 3.0, 5.0, 2.0 };
    const char* phaseNames[] = {
        "Shift weight RIGHT", "LEFT foot lifted", "Lowering LEFT foot",
        "Shift weight LEFT",  "RIGHT foot lifted", "Lowering RIGHT foot"
    };

    while (balanceRunning && currentPhase < 6) {
        double loopStart = getTimeSeconds();
        double t = loopStart - startTime;
        double phaseT = loopStart - phaseStartTime;
        double phaseDur = phaseDurations[currentPhase];
        double t01 = fmin(1.0, phaseT / phaseDur);

        imuUpdate();
        double dt = loopStart - lastLoopTime;
        lastLoopTime = loopStart;
        if (dt < 0.005 || dt > 0.2) dt = 0.030;
        balanceUpdate(dt);

        if (!safetyCheck()) break;

        // Gait servo values - all start at center
        double rTurn = 0, rHip = 0, rKnee = 0;
        double lTurn = 0, lHip = 0, lKnee = 0;

        switch (currentPhase) {
        case 0:  // Shift weight onto right foot
            rTurn = -WALK_TURN_SHIFT * t01;
            lTurn = -WALK_TURN_SHIFT * t01;
            break;
        case 1:  // Left foot lifted
            rTurn = -WALK_TURN_SHIFT;
            lTurn = -WALK_TURN_SHIFT;
            lKnee = 10.0;  // Lift left knee slightly
            break;
        case 2:  // Lower left foot
            rTurn = -WALK_TURN_SHIFT * (1.0 - t01);
            lTurn = -WALK_TURN_SHIFT * (1.0 - t01);
            lKnee = 10.0 * (1.0 - t01);
            break;
        case 3:  // Shift weight onto left foot
            rTurn = WALK_TURN_SHIFT * t01;
            lTurn = WALK_TURN_SHIFT * t01;
            break;
        case 4:  // Right foot lifted
            rTurn = WALK_TURN_SHIFT;
            lTurn = WALK_TURN_SHIFT;
            rKnee = 10.0;  // Lift right knee slightly
            break;
        case 5:  // Lower right foot
            rTurn = WALK_TURN_SHIFT * (1.0 - t01);
            lTurn = WALK_TURN_SHIFT * (1.0 - t01);
            rKnee = 10.0 * (1.0 - t01);
            break;
        }

        // Ankles: balance correction on SUPPORT foot only.
        // Lifted foot stays at center (flapping in air causes IMU feedback loop!)
        // Phases 0,1,2 = right foot planted; Phases 3,4,5 = left foot planted
        bool rightPlanted = (currentPhase <= 2);
        bool leftPlanted = (currentPhase >= 3);

        // During shift phases (0, 2, 3, 5) both feet are on ground
        if (currentPhase == 0 || currentPhase == 2) leftPlanted = true;
        if (currentPhase == 3 || currentPhase == 5) rightPlanted = true;

        int ankleR = rightPlanted
            ? clampServo(SERVO_CENTER + (int)(bal.ankleCorrection * DIR_RIGHT_FOOT))
            : SERVO_CENTER;
        int ankleL = leftPlanted
            ? clampServo(SERVO_CENTER + (int)(bal.ankleCorrection * DIR_LEFT_FOOT))
            : SERVO_CENTER;

        pRightFootServo->Move(ankleR);
        pLeftFootServo->Move(ankleL);

        // Round-robin gait servo
        int gaitVals[6];
        gaitVals[0] = clampServo(SERVO_CENTER + (int)((rHip + bal.hipCorrection) * DIR_RIGHT_HIP));
        gaitVals[1] = clampServo(SERVO_CENTER + (int)((lHip + bal.hipCorrection) * DIR_LEFT_HIP));
        gaitVals[2] = clampServo(SERVO_CENTER + (int)(rKnee * DIR_RIGHT_KNEE));
        gaitVals[3] = clampServo(SERVO_CENTER + (int)(lKnee * DIR_LEFT_KNEE));
        switch (gaitServoIndex) {
        case 0: pRightHipServo->Move(gaitVals[0]); break;
        case 1: pLeftHipServo->Move(gaitVals[1]); break;
        case 2: pRightKneeServo->Move(gaitVals[2]); break;
        case 3: pLeftKneeServo->Move(gaitVals[3]); break;
        }
        gaitServoIndex = (gaitServoIndex + 1) % 4;

        // Phase transition
        if (phaseT >= phaseDur) {
            printf("Phase %d complete: %s (pitch=%.1f, roll=%.1f)\n",
                currentPhase, phaseNames[currentPhase], imu.pitch, imu.roll);
            currentPhase++;
            phaseStartTime = loopStart;
        }

        // Print status every ~500ms
        static double lastPrint = 0;
        if (loopStart - lastPrint >= 0.5) {
            printf("[%s] t=%4.1f  Pitch=%5.1f  Roll=%5.1f  Ankle=%5.1f  dt=%.0fms\n",
                phaseNames[currentPhase < 6 ? currentPhase : 5],
                t, imu.pitch, imu.roll, bal.ankleCorrection, dt * 1000);
            lastPrint = loopStart;
        }

        enforceMinLoopTime(loopStart);
    }

    centerAllServos();
    printf("Single leg stand test complete.\n");
}


// ============================================================
// MODE 2: WEIGHT SHIFT TEST
// ============================================================

void balanceWeightShiftTest() {
    printf("=== WEIGHT SHIFT TEST MODE ===\n");
    printf("Slowly shifting weight left/right with balance active.\n");
    printf("Round-robin: 2 ankles + 1 gait servo per cycle = ~30ms = 33Hz balance.\n\n");

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;
    bal.pitchIntegral = 0;
    bal.rollIntegral = 0;
    imu.initialized = false;

    double startTime = getTimeSeconds();
    double lastLoopTime = startTime;
    int gaitServoIndex = 0;  // Round-robin: 0-5 for the 6 non-ankle servos

    // Cached gait servo values (updated each cycle, sent one at a time)
    int gaitServoVal[6] = { SERVO_CENTER, SERVO_CENTER, SERVO_CENTER,
                           SERVO_CENTER, SERVO_CENTER, SERVO_CENTER };

    while (balanceRunning) {
        double loopStart = getTimeSeconds();
        double t = loopStart - startTime;

        imuUpdate();
        double dt = loopStart - lastLoopTime;
        lastLoopTime = loopStart;
        if (dt < 0.005 || dt > 0.2) dt = 0.030;
        balanceUpdate(dt);

        if (!safetyCheck()) break;

        // Sinusoidal weight shift: period = 4 seconds
        double shiftPhase = sin(2.0 * M_PI * t / 4.0);
        double turnShift = WALK_TURN_SHIFT * shiftPhase;
        double hipShift = 3.0 * shiftPhase;

        // Compute all gait servo targets (cached for round-robin sending)
        gaitServoVal[0] = clampServo(SERVO_CENTER + (int)((hipShift + bal.hipCorrection) * DIR_RIGHT_HIP));
        gaitServoVal[1] = clampServo(SERVO_CENTER + (int)((hipShift + bal.hipCorrection) * DIR_LEFT_HIP));
        gaitServoVal[2] = clampServo(SERVO_CENTER);  // knees centered
        gaitServoVal[3] = clampServo(SERVO_CENTER);
        // Always update ankles
        double rFoot = bal.ankleCorrection;
        double lFoot = bal.ankleCorrection;
        pRightFootServo->Move(clampServo(SERVO_CENTER + (int)(rFoot * DIR_RIGHT_FOOT)));
        pLeftFootServo->Move(clampServo(SERVO_CENTER + (int)(lFoot * DIR_LEFT_FOOT)));

        // Round-robin: send 1 gait servo per cycle
        switch (gaitServoIndex) {
        case 0: pRightHipServo->Move(gaitServoVal[0]); break;
        case 1: pLeftHipServo->Move(gaitServoVal[1]); break;
        case 2: pRightKneeServo->Move(gaitServoVal[2]); break;
        case 3: pLeftKneeServo->Move(gaitServoVal[3]); break;
        }
        gaitServoIndex = (gaitServoIndex + 1) % 4;

        // Print status every ~500ms
        static double lastPrint = 0;
        if (loopStart - lastPrint >= 0.5) {
            printf("t=%5.1f  shift=%5.1f  Pitch=%5.1f  Roll=%5.1f  Ankle=%5.1f  dt=%.0fms\n",
                t, turnShift, imu.pitch, imu.roll, bal.ankleCorrection, dt * 1000);
            lastPrint = loopStart;
        }

        enforceMinLoopTime(loopStart);
    }

    centerAllServos();
    printf("Weight shift test stopped.\n");
}


// ============================================================
// HIP ROLL DIRECTION TEST
// Cycles through -20, -10, 0, +10, +20 deg hip roll.
// Holds each for 3 seconds and prints actual Roll angle.
// Use this to find which gait sign leans body LEFT vs RIGHT.
// ============================================================

void hipRollDirectionTest() {
    printf("=== HIP ROLL DIRECTION TEST ===\n");
    printf("Holds each angle 3s. Watch body lean and note roll sign.\n");
    printf("Positive roll = leaning RIGHT. Negative roll = leaning LEFT.\n\n");

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;
    imu.initialized = false;

    double angles[] = { -20.0, -10.0, 0.0, 10.0, 20.0 };
    int nAngles = 5;

    for (int ai = 0; ai < nAngles && balanceRunning; ai++) {
        double cmd = angles[ai];
        printf("--- Hip roll command = %+.0f deg (hip roll removed from robot)\n", cmd);

        double holdStart = getTimeSeconds();
        double lastLoop = holdStart;
        double lastPrint = 0;

        while (balanceRunning) {
            double now = getTimeSeconds();
            double elapsed = (now - holdStart) * 1000.0;

            imuUpdate();
            double dt = now - lastLoop;
            lastLoop = now;
            if (dt < 0.005 || dt > 0.2) dt = 0.030;
            // No balance update - raw servo command only (hip roll removed from robot)
            pRightFootServo->Move(SERVO_CENTER);
            pLeftFootServo->Move(SERVO_CENTER);
            pRightHipServo->Move(SERVO_CENTER);
            pLeftHipServo->Move(SERVO_CENTER);
            pRightKneeServo->Move(SERVO_CENTER);
            pLeftKneeServo->Move(SERVO_CENTER);

            if (now - lastPrint > 0.5) {
                lastPrint = now;
                printf("  t=%3.0fs  Roll=%5.1f  Pitch=%5.1f\n",
                    elapsed / 1000.0, imu.roll, imu.pitch);
            }

            if (elapsed >= 3000.0) break;
            enforceMinLoopTime(holdStart + elapsed / 1000.0);
            usleep(30000);
        }
        printf("  -> Roll at cmd=%+.0f: avg %.1f deg  (positive=RIGHT, negative=LEFT)\n\n",
            cmd, imu.roll);
    }

    centerAllServos();
    printf("Direction test complete.\n");
    printf("After this test you should know:\n");
    printf("  Which CMD sign causes rightward lean (use that sign in footLiftTest)\n");
    printf("  How many degrees of Roll per degree of CMD (the gain ratio)\n");
}


// ============================================================
// FOOT LIFT TEST
// Phase 1: Shift weight to RIGHT foot via hip roll + support knee bend.
// Phase 2: Attempt to lift LEFT foot at increasing knee angles.
// With DIR_HIP_ROLL=-1: positive hipRollGait = servo above 90 = legs
//   go LEFT = body leans RIGHT = weight on right foot.
// ============================================================

void footLiftTest() {
    printf("=== FOOT LIFT TEST ===\n");
    printf("Phase 1: Lean body RIGHT (hip roll + support knee bend).\n");
    printf("Phase 2: Lift LEFT knee at increasing angles.\n");
    printf("Watch LEFT foot - note when it clears ground.\n\n");

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;
    bal.pitchIntegral = 0;
    bal.rollIntegral = 0;
    imu.initialized = false;

    // With DIR_HIP_ROLL=-1: servo = 90 + gait*(-1) = 90 - gait.
    // CONFIRMED by direction test:
    //   positive gait -> servo below 90 -> body leans RIGHT (positive roll)
    //   negative gait -> servo above 90 -> body leans LEFT  (negative roll)
    // At +10 the silicone grip holds (barely any lean).
    // At +20 the robot clearly tips right (+16 deg) but oscillates if instantaneous.
    // Slow 3-second ramp to +18 should give stable rightward lean without violent swing.
    // CONFIRMED direction: positive gait -> servo below 90 -> body leans RIGHT.
    // +20 is too violent (overshoot causes ±30 deg oscillation).
    // Start with +10 (barely any lean, safe) and ramp slowly.
    // Increase to 12, 14, 16 if roll stays small - find the lean threshold gently.
    const double HIP_ROLL_SHIFT = 10.0;  // Start small - increase gradually
    const double SUPPORT_KNEE_BEND = 0.0;  // DISABLED: causes forward pitch

    // Helper: send all servos.
    // hipRollGait: positive tilts body RIGHT (with DIR_HIP_ROLL=-1 baked in)
    // lKneeGait:   left (swing) knee lift angle
    // rKneeBend:   right (support) knee bend angle (lowers right side, shifts CoM right)
    auto sendServos = [&](double hipRollGait, double lKneeGait, double rKneeBend) {
        pRightFootServo->Move(clampServo(SERVO_CENTER + (int)(bal.ankleCorrection * DIR_RIGHT_FOOT)));
        pLeftFootServo->Move(clampServo(SERVO_CENTER + (int)(bal.ankleCorrection * DIR_LEFT_FOOT)));
        pRightHipServo->Move(clampServo(SERVO_CENTER + (int)(bal.hipCorrection * DIR_RIGHT_HIP)));
        pLeftHipServo->Move(clampServo(SERVO_CENTER + (int)(bal.hipCorrection * DIR_LEFT_HIP)));
        pRightKneeServo->Move(clampServo(SERVO_CENTER + (int)(rKneeBend * DIR_RIGHT_KNEE)));
        pLeftKneeServo->Move(clampServo(SERVO_CENTER + (int)(lKneeGait * DIR_LEFT_KNEE)));
        };

    // Phase 1: Ramp hip roll + support knee together over 3 seconds
    printf("Phase 1: Slowly leaning RIGHT (hip_roll=%.0f over 5s)...\n", HIP_ROLL_SHIFT);
    double phaseStart = getTimeSeconds();
    double shiftDur = 5000.0;  // 5s ramp - slow enough to avoid servo overshoot oscillation
    double lastLoop = phaseStart;

    while (balanceRunning) {
        double loopStart = getTimeSeconds();
        double elapsed = (loopStart - phaseStart) * 1000.0;
        double t = fmin(1.0, elapsed / shiftDur);

        imuUpdate();
        double dt = loopStart - lastLoop;
        lastLoop = loopStart;
        if (dt < 0.005 || dt > 0.2) dt = 0.030;
        balanceUpdate(dt);

        if (!safetyCheck()) { centerAllServos(); return; }
        sendServos(HIP_ROLL_SHIFT * t, 0.0, SUPPORT_KNEE_BEND * t);

        if (elapsed >= shiftDur) break;
        enforceMinLoopTime(loopStart);
    }
    printf("Weight shifted. Pitch=%.1f  Roll=%.1f  (positive roll = leaning RIGHT = good)\n\n",
        imu.pitch, imu.roll);

    // Phase 2: Hold weight shift, lift left (swing) knee at increasing angles
    // Small steps: find exactly when foot clears ground
    double testAngles[] = { 3, 5, 8, 10, 13, 15, 20 };
    int numAngles = 7;

    for (int ai = 0; ai < numAngles && balanceRunning; ai++) {
        double liftAngle = testAngles[ai];
        printf("--- Left knee lift: %.0f deg ---\n", liftAngle);

        phaseStart = getTimeSeconds();
        double rampDur = 3000.0;  // slow ramp to avoid servo overshoot oscillation
        double holdDur = 3000.0;
        lastLoop = phaseStart;

        while (balanceRunning) {
            double loopStart = getTimeSeconds();
            double elapsed = (loopStart - phaseStart) * 1000.0;

            imuUpdate();
            double dt = loopStart - lastLoop;
            lastLoop = loopStart;
            if (dt < 0.005 || dt > 0.2) dt = 0.030;
            balanceUpdate(dt);

            if (!safetyCheck()) {
                printf("FELL at %.0f deg lift! (pitch=%.1f, roll=%.1f)\n",
                    liftAngle, imu.pitch, imu.roll);
                centerAllServos();
                return;
            }

            double t = fmin(1.0, elapsed / rampDur);
            double lKnee = liftAngle * t;
            sendServos(HIP_ROLL_SHIFT, lKnee, SUPPORT_KNEE_BEND);

            static double lastPrint = 0;
            if (loopStart - lastPrint > 0.5) {
                lastPrint = loopStart;
                printf("  Lift=%4.1f  Pitch=%5.1f  Roll=%5.1f  AnkleCorr=%5.1f\n",
                    lKnee, imu.pitch, imu.roll, bal.ankleCorrection);
            }

            if (elapsed >= rampDur + holdDur) break;
            enforceMinLoopTime(loopStart);
        }

        printf("  Held %.0f deg. Did LEFT foot clear ground?\n\n", liftAngle);
        usleep(300000);
    }

    centerAllServos();
    printf("Foot lift test complete.\n");
}


// ============================================================
// IMU ORIENTATION TEST
// Prints pitch/roll for 30s while you tilt the robot manually.
// Verify: forward lean = pitch+, right lean = roll+
// ============================================================

void imuTest() {
    printf("=== BNO055 ORIENTATION TEST ===\n");
    printf("Tilt the robot slowly and verify sign conventions:\n");
    printf("  Lean FORWARD  -> Pitch should be POSITIVE\n");
    printf("  Lean BACKWARD -> Pitch should be NEGATIVE\n");
    printf("  Lean RIGHT    -> Roll  should be POSITIVE\n");
    printf("  Lean LEFT     -> Roll  should be NEGATIVE\n");
    printf("Running 30 seconds (Ctrl+C to stop early)...\n\n");

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;
    imu.initialized = false;

    double startTime = getTimeSeconds();
    double lastPrint = 0;

    while (balanceRunning && (getTimeSeconds() - startTime) < 30.0) {
        imuUpdate();
        double now = getTimeSeconds();
        if (now - lastPrint >= 0.2) {
            printf("t=%4.1f  Pitch=%+6.1f  PitchRate=%+6.1f  Roll=%+6.1f  RollRate=%+6.1f\n",
                now - startTime, imu.pitch, imu.pitchRate, imu.roll, imu.rollRate);
            lastPrint = now;
        }
        usleep(20000);
    }
    printf("IMU test complete.\n");
}


// ============================================================
// SERVO DIRECTION TEST
// Tests each servo individually: +angle for 3s, then -angle for 3s.
// Prints roll/pitch so you can record which sign = which direction.
// HOLD the robot - some poses will be unstable.
// ============================================================

void servoDirectionTest() {
    printf("=== SERVO DIRECTION TEST ===\n");
    printf("Each servo tested one at a time: +angle for 3s, center, -angle for 3s.\n");
    printf("HOLD the robot - some poses are unstable!\n");
    printf("Sign convention to verify: Roll+ = lean right, Pitch+ = lean forward\n\n");

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;
    imu.initialized = false;

    const char* servoNames[] = {
        "RIGHT ANKLE ROLL", "LEFT ANKLE ROLL",
        "RIGHT HIP PITCH",  "LEFT HIP PITCH",
        "RIGHT KNEE",       "LEFT KNEE"
    };
    double testAngles[] = { 15, 15, 20, 20, 20, 20 };
    int nServos = 6;

    for (int si = 0; si < nServos && balanceRunning; si++) {
        printf("========================================\n");
        printf("SERVO: %s\n", servoNames[si]);
        printf("========================================\n");

        for (int sign = 1; sign >= -1 && balanceRunning; sign -= 2) {
            double cmd = testAngles[si] * sign;
            int pos = clampServo(SERVO_CENTER + (int)cmd);

            centerAllServos();
            usleep(400000);

            printf("  %+.0f deg -> servo position %d\n", cmd, pos);

            switch (si) {
            case 0: pRightFootServo->Move(pos);     break;
            case 1: pLeftFootServo->Move(pos);      break;
            case 2: pRightHipServo->Move(pos);      break;
            case 3: pLeftHipServo->Move(pos);       break;
            case 4: pRightKneeServo->Move(pos);     break;
            case 5: pLeftKneeServo->Move(pos);      break;
            }

            double tStart = getTimeSeconds();
            double lastPrint = 0;
            while ((getTimeSeconds() - tStart) < 3.0 && balanceRunning) {
                imuUpdate();
                double now = getTimeSeconds();
                if (now - lastPrint >= 0.5) {
                    printf("    Roll=%+5.1f  Pitch=%+5.1f\n", imu.roll, imu.pitch);
                    lastPrint = now;
                }
                usleep(30000);
            }
        }
        printf("  -> %s done.\n\n", servoNames[si]);
    }

    centerAllServos();
    printf("Servo direction test complete.\n");
    printf("Update DIR_* constants in the code based on your observations.\n");
}


// ============================================================
// MODE 3: WALKING WITH BALANCE
// ============================================================

void balanceWalk() {
    printf("=== WALKING MODE ===\n");
    printf("Hip: %.1f deg  Knee: %.1f deg  AnkleShift: %.1f deg  Step: %.0f ms  Shift: %.0f ms\n",
        WALK_HIP_AMPLITUDE, WALK_KNEE_LIFT, WALK_ANKLE_SHIFT,
        WALK_STEP_PERIOD_MS, WALK_WEIGHT_SHIFT_MS);
    printf("RollKp=%.2f  PitchKp=%.2f  Press Ctrl+C to stop.\n\n",
        ROLL_KP_ANKLE, PITCH_KP_HIP);

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;
    bal.pitchIntegral = 0;
    bal.rollIntegral = 0;
    imu.initialized = false;

    // 6-phase walking cycle - ANKLE ROLL weight shift:
    //   Right support: both ankles NEGATIVE (below 90) to shift COM right.
    //   Left  support: both ankles POSITIVE (above 90) to shift COM left.
    //
    // 0: SHIFT_RIGHT - rAnkle=-S (support), lAnkle=-push bell; hips neutral
    // 1: SWING_LEFT  - rAnkle holds -S; left foot swings forward
    // 2: SETTLE      - rAnkle returns to 0, balance re-establishes
    // 3: SHIFT_LEFT  - lAnkle=+S (support), rAnkle=+push bell; hips neutral
    // 4: SWING_RIGHT - lAnkle holds +S; right foot swings forward
    // 5: SETTLE      - lAnkle returns to 0
    int walkPhase = 0;
    double phaseStartTime = getTimeSeconds();
    int stepCount = 0;
    double lastLoopTime = phaseStartTime;

    double shiftDur = WALK_WEIGHT_SHIFT_MS;        // ms
    double stepDur = WALK_STEP_PERIOD_MS;          // ms
    double settleDur = WALK_WEIGHT_SHIFT_MS * 0.8;  // ms

    const char* phaseNames[] = {
        "SHIFT_R", "STEP_L", "SETTLE",
        "SHIFT_L", "STEP_R", "SETTLE"
    };

    double A = WALK_HIP_AMPLITUDE;
    double S = WALK_ANKLE_SHIFT;

    double rHip = 0, lHip = 0;
    double rKnee = 0, lKnee = 0;
    double rAnkle = 0, lAnkle = 0;  // Ankle roll gait component (weight shift)

    while (balanceRunning) {
        double loopStart = getTimeSeconds();
        double phaseElapsed = (loopStart - phaseStartTime) * 1000.0;  // ms

        imuUpdate();
        double dt = loopStart - lastLoopTime;
        lastLoopTime = loopStart;
        if (dt < 0.005 || dt > 0.2) dt = 0.030;
        balanceUpdate(dt);

        if (!safetyCheck()) break;

        double phaseDur = 0;
        bool phaseComplete = false;

        switch (walkPhase) {
        case 0: {  // SHIFT_RIGHT: roll both ankles right, bring hips back to neutral
            phaseDur = shiftDur;
            double t = fmin(1.0, phaseElapsed / phaseDur);
            rAnkle = S * t;
            lAnkle = S * t;
            rHip = (stepCount == 0) ? 0 : A * (1.0 - t);  // swing-side hip returns to neutral
            lHip = 0;  // support hip stays neutral (was -A*(1-t) which wasted correction range)
            rKnee = 0; lKnee = 0;
            if (phaseElapsed >= phaseDur) phaseComplete = true;
            break;
        }
        case 1: {  // STEP_LEFT: swing left foot forward while right foot supports
            phaseDur = stepDur;
            double t = fmin(1.0, phaseElapsed / phaseDur);
            rAnkle = S;   // Support ankle holds shift
            lAnkle = (t < 0.15) ? S * (1.0 - t / 0.15) : 0.0;  // Ramp swing ankle down over 300ms (avoid sudden jerk)
            // Hip swings simultaneously with knee from t=0 (prevents backward pitch impulse)
            if (t < 0.70) {
                double s = t / 0.70;
                lKnee = WALK_KNEE_LIFT * fmin(1.0, s * 1.5);  // knee up in first 67% of swing
                lHip = A * s;
                rHip = 0;
            }
            else if (t < 0.85) {
                double s = (t - 0.70) / 0.15;
                lKnee = WALK_KNEE_LIFT * (1.0 - s);
                lHip = A; rHip = 0;
            }
            else {
                lKnee = 0; lHip = A; rHip = 0;
            }
            if (phaseElapsed >= phaseDur) phaseComplete = true;
            break;
        }
        case 2: {  // SETTLE: return right ankle to neutral, hips stay, balance settles
            phaseDur = settleDur;
            double t = fmin(1.0, phaseElapsed / phaseDur);
            rAnkle = S * (1.0 - t);
            lAnkle = 0;
            rHip = 0; lHip = A;
            rKnee = 0; lKnee = 0;
            if (phaseElapsed >= phaseDur) phaseComplete = true;
            break;
        }
        case 3: {  // SHIFT_LEFT: roll both ankles left, bring hips back to neutral
            phaseDur = shiftDur;
            double t = fmin(1.0, phaseElapsed / phaseDur);
            rAnkle = -S * t;
            lAnkle = -S * t;
            rHip = 0;
            lHip = A * (1.0 - t);
            rKnee = 0; lKnee = 0;
            if (phaseElapsed >= phaseDur) phaseComplete = true;
            break;
        }
        case 4: {  // STEP_RIGHT: swing right foot forward while left foot supports
            phaseDur = stepDur;
            double t = fmin(1.0, phaseElapsed / phaseDur);
            lAnkle = -S;  // Support ankle holds shift
            rAnkle = (t < 0.15) ? -S * (1.0 - t / 0.15) : 0.0;  // Ramp swing ankle down over 300ms
            // Hip swings simultaneously with knee from t=0
            if (t < 0.70) {
                double s = t / 0.70;
                rKnee = WALK_KNEE_LIFT * fmin(1.0, s * 1.5);
                rHip = A * s;
                lHip = 0;
            }
            else if (t < 0.85) {
                double s = (t - 0.70) / 0.15;
                rKnee = WALK_KNEE_LIFT * (1.0 - s);
                rHip = A; lHip = 0;
            }
            else {
                rKnee = 0; rHip = A; lHip = 0;
            }
            if (phaseElapsed >= phaseDur) phaseComplete = true;
            break;
        }
        case 5: {  // SETTLE: return left ankle to neutral
            phaseDur = settleDur;
            double t = fmin(1.0, phaseElapsed / phaseDur);
            lAnkle = -S * (1.0 - t);
            rAnkle = 0;
            rHip = A; lHip = 0;
            rKnee = 0; lKnee = 0;
            if (phaseElapsed >= phaseDur) phaseComplete = true;
            break;
        }
        }

        // ANKLE SERVOS: gait shift + whole-body roll balance correction.
        // Key insight: ankle roll shifts weight but barely moves the IMU (torso stays near upright).
        // bal.ankleCorrection targets 0 deg whole-body tilt — correct for standing balance.
        // Swing foot gets no correction (in air). Ramp swing ankle to 0 over first 15% of step.
        double rAnkleBalance = (walkPhase == 4) ? 0.0 : bal.ankleCorrection;
        double lAnkleBalance = (walkPhase == 1) ? 0.0 : bal.ankleCorrection;
        pRightFootServo->Move(clampServo(SERVO_CENTER + (int)((rAnkle + rAnkleBalance) * DIR_RIGHT_FOOT)));
        pLeftFootServo->Move(clampServo(SERVO_CENTER + (int)((lAnkle + lAnkleBalance) * DIR_LEFT_FOOT)));

        // HIP SERVOS: gait position + walk-specific pitch balance correction.
        // Walk needs higher gain than balanceStand: single-leg stance is ~4x less stable.
        // CRITICAL: apply correction only to the SUPPORT leg during step phases.
        // Applying it to the swing leg creates a runaway feedback loop:
        //   pitch backward -> correction reduces swing-leg forward motion
        //   -> less body-forward contribution -> worse pitch -> more correction -> crash.
        double predictedPitchW = imu.pitch + imu.pitchRate * WALK_LOOK_AHEAD;
        double pitchErrorW = predictedPitchW - COM_FORWARD_LEAN_DEG;
        double walkHipCorr = 0.0;
        if (fabs(pitchErrorW) > WALK_DEADBAND) {
            double effErrW = pitchErrorW > 0.0 ? pitchErrorW - WALK_DEADBAND : pitchErrorW + WALK_DEADBAND;
            // KP: proportional to predicted error; KD: damps rapid pitch rate (negative sign = flexion corrects lean)
            walkHipCorr = -(WALK_PITCH_KP * effErrW + WALK_PITCH_KD * imu.pitchRate);
            if (walkHipCorr > WALK_HIP_LIMIT) walkHipCorr = WALK_HIP_LIMIT;
            if (walkHipCorr < -WALK_HIP_LIMIT) walkHipCorr = -WALK_HIP_LIMIT;
        }
        // Apply walkHipCorr to both hips at all times.
        // With support hip = 0 throughout non-swing phases, all phase transitions are
        // continuous (gait hip values match at every boundary), so no exclusions needed.
        // Both hips correcting doubles the effective torque vs single-hip correction.
        int gv[4];
        gv[0] = clampServo(SERVO_CENTER + (int)((rHip + walkHipCorr) * DIR_RIGHT_HIP));
        gv[1] = clampServo(SERVO_CENTER + (int)((lHip + walkHipCorr) * DIR_LEFT_HIP));
        gv[2] = clampServo(SERVO_CENTER + (int)(rKnee * DIR_RIGHT_KNEE));
        gv[3] = clampServo(SERVO_CENTER + (int)(lKnee * DIR_LEFT_KNEE));
        // Update all servos every loop - balance correction must reach servo each cycle.
        pRightHipServo->Move(gv[0]);   pLeftHipServo->Move(gv[1]);
        pRightKneeServo->Move(gv[2]);  pLeftKneeServo->Move(gv[3]);

        // Diagnostic: print every ~100ms during step phases to trace pitch trend
        if (walkPhase == 1 || walkPhase == 4) {
            static double lastStepPrint = -100.0;
            static int    lastStepPhase = -1;
            if (walkPhase != lastStepPhase) { lastStepPrint = -100.0; lastStepPhase = walkPhase; }
            if (phaseElapsed - lastStepPrint >= 100.0) {
                lastStepPrint = phaseElapsed;
                printf("  [t=%.0f] p=%.1f hc=%.1f rHipSv=%d lHipSv=%d lKnSv=%d\n",
                    phaseElapsed, imu.pitch, walkHipCorr,
                    gv[0], gv[1], gv[3]);
            }
        }

        if (phaseComplete) {
            printf("Step %d: %s done (pitch=%.1f hipCorr=%.1f, roll=%.1f ankCorr=%.1f, rHip=%.1f, lHip=%.1f, rAnkle=%.1f, lAnkle=%.1f)\n",
                stepCount, phaseNames[walkPhase],
                imu.pitch, walkHipCorr, imu.roll, bal.ankleCorrection, rHip, lHip, rAnkle, lAnkle);
            walkPhase = (walkPhase + 1) % 6;
            phaseStartTime = loopStart;
            if (walkPhase == 0) stepCount++;
        }

        enforceMinLoopTime(loopStart);
    }

    centerAllServos();
    printf("Walking stopped after %d steps.\n", stepCount);
}


// ============================================================
// SMOOTH SINGLE-LEG BALANCE TEST
// Run this before walkSmooth() to verify the ankle-shift parameters
// are sufficient for single-leg stance, using the exact same ankle
// motions the walk will use.  Tune SW_ANKLE_SHIFT here first.
// ============================================================

void testSingleLegSmooth() {
    printf("=== SINGLE-LEG BALANCE TEST ===\n");
    printf("AnkleShift=%.1f  (swing foot rises naturally when COM clears support foot)\n", SW_ANKLE_SHIFT);
    printf("Transition=%.0fms  Hold=%.0fms\n\n", SW_TRANS_MS, SW_HOLD_MS);
    printf("Sequence (each side): SHIFT -> SETTLE -> HOLD -> RETURN -> REST\n\n");

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;
    imu.initialized = false;

    // --- Initial IMU sanity check (before any movement) ---
    {
        imuUpdate();
        printf("Initial tilt (robot still): pitch=%.1f  roll=%.1f\n\n", imu.pitch, imu.roll);
        if (fabs(imu.pitch) > 20.0 || fabs(imu.roll) > 20.0) {
            printf("WARNING: Robot is not upright (tilt > 20 deg). Place robot flat before starting.\n");
            printf("         Aborting.\n\n");
            centerAllServos();
            return;
        }
    }

    for (int side = 0; side < 2 && balanceRunning; side++) {
        bool rightSupport = (side == 0);
        printf("%s\n", rightSupport ? "--- RIGHT support, LEFT lifted ---"
            : "--- LEFT support, RIGHT lifted ---");

        // SHIFT: roll support ankle in smoothly; other ankle gives a bell push.
        // Hips and knees stay at base - ankle roll alone shifts COM laterally.
        {
            printf("  SHIFT   (%.0fms)...", SW_TRANS_MS); fflush(stdout);
            double t0 = getTimeSeconds();
            while (balanceRunning) {
                double t = (getTimeSeconds() - t0) * 1000.0 / SW_TRANS_MS;
                if (t > 1.0) t = 1.0;
                double st = smoothstep(t);
                if (rightSupport)
                    setLegs(0, 0, SW_KNEE_BASE, SW_KNEE_BASE,
                        -SW_ANKLE_SHIFT * st,
                        -SW_ANKLE_PUSH * st);
                else
                    setLegs(0, 0, SW_KNEE_BASE, SW_KNEE_BASE,
                        +SW_ANKLE_PUSH * st,
                        +SW_ANKLE_SHIFT_L * st);  // left support uses reduced value
                imuUpdate();
                if (fabs(imu.pitch) > MAX_TILT_DEG || fabs(imu.roll) > MAX_TILT_DEG) {
                    printf("\n  EMERGENCY during SHIFT: pitch=%.1f roll=%.1f\n",
                        imu.pitch, imu.roll);
                    balanceRunning = false; break;
                }
                if (t >= 1.0) break;
                usleep(10000);
            }
            if (balanceRunning) printf(" done (pitch=%.1f roll=%.1f)\n", imu.pitch, imu.roll);
        }

        // SETTLE: brief pause after shift - swing foot should now be off the ground
        {
            printf("  SETTLE  (300ms)..."); fflush(stdout);
            double t0 = getTimeSeconds();
            while (balanceRunning) {
                imuUpdate();
                if (rightSupport)
                    setLegs(0, 0, SW_KNEE_BASE, SW_KNEE_BASE, -SW_ANKLE_SHIFT, -SW_ANKLE_PUSH);
                else
                    setLegs(0, 0, SW_KNEE_BASE, SW_KNEE_BASE, +SW_ANKLE_PUSH, +SW_ANKLE_SHIFT_L);
                if (fabs(imu.pitch) > MAX_TILT_DEG || fabs(imu.roll) > MAX_TILT_DEG) {
                    printf("\n  EMERGENCY during SETTLE: pitch=%.1f roll=%.1f\n",
                        imu.pitch, imu.roll);
                    balanceRunning = false; break;
                }
                if (getTimeSeconds() - t0 >= 0.3) break;
                usleep(10000);
            }
            if (balanceRunning) printf(" done (pitch=%.1f roll=%.1f)\n", imu.pitch, imu.roll);
        }

        // HOLD: maintain fixed ankle angles — no active correction.
        // Static ankle shift alone is sufficient to hold COM over support foot.
        // Active correction caused oscillation due to marginal foot clearance.
        {
            printf("  HOLD    (%.0fms)  ", SW_HOLD_MS); fflush(stdout);
            double t0 = getTimeSeconds();
            double nextPrint = 1.0;
            while (balanceRunning) {
                double elapsed = (getTimeSeconds() - t0) * 1000.0;
                if (elapsed >= SW_HOLD_MS) break;
                if (elapsed >= nextPrint * 1000.0) {
                    printf("%.0f... ", nextPrint); fflush(stdout);
                    nextPrint += 1.0;
                }
                imuUpdate();
                if (fabs(imu.pitch) > MAX_TILT_DEG || fabs(imu.roll) > MAX_TILT_DEG) {
                    printf("\nEMERGENCY: tilt (pitch=%.1f roll=%.1f)\n",
                        imu.pitch, imu.roll);
                    balanceRunning = false; break;
                }
                if (rightSupport)
                    setLegs(0, 0, SW_KNEE_BASE, SW_KNEE_BASE, -SW_ANKLE_SHIFT, -SW_ANKLE_PUSH);
                else
                    setLegs(0, 0, SW_KNEE_BASE, SW_KNEE_BASE, +SW_ANKLE_PUSH, +SW_ANKLE_SHIFT_L);
                usleep(10000);
            }
            printf("done\n");
        }

        // LOWER: renamed to just a pre-return pause (no knee was lifted)
        {
            printf("  LOWER   (%.0fms)...", SW_TRANS_MS); fflush(stdout);
            double t0 = getTimeSeconds();
            while (balanceRunning) {
                double t = (getTimeSeconds() - t0) * 1000.0 / SW_TRANS_MS;
                if (t > 1.0) t = 1.0;
                if (rightSupport)
                    setLegs(0, 0, SW_KNEE_BASE, SW_KNEE_BASE, -SW_ANKLE_SHIFT, -SW_ANKLE_PUSH);
                else
                    setLegs(0, 0, SW_KNEE_BASE, SW_KNEE_BASE, +SW_ANKLE_PUSH, +SW_ANKLE_SHIFT_L);
                if (t >= 1.0) break;
                usleep(10000);
            }
            printf(" done\n");
        }

        // RETURN: ramp both ankles back to neutral together
        {
            printf("  RETURN  (%.0fms)...", SW_TRANS_MS); fflush(stdout);
            double t0 = getTimeSeconds();
            while (balanceRunning) {
                double t = (getTimeSeconds() - t0) * 1000.0 / SW_TRANS_MS;
                if (t > 1.0) t = 1.0;
                double st = 1.0 - smoothstep(t);
                if (rightSupport)
                    setLegs(0, 0, SW_KNEE_BASE, SW_KNEE_BASE,
                        -SW_ANKLE_SHIFT * st, -SW_ANKLE_PUSH * st);
                else
                    setLegs(0, 0, SW_KNEE_BASE, SW_KNEE_BASE,
                        +SW_ANKLE_PUSH * st, +SW_ANKLE_SHIFT_L * st);
                if (t >= 1.0) break;
                usleep(10000);
            }
            printf(" done\n");
        }

        // REST: both feet flat before mirroring
        if (side == 0 && balanceRunning) {
            printf("  REST    (1000ms)..."); fflush(stdout);
            double t0 = getTimeSeconds();
            while (balanceRunning && (getTimeSeconds() - t0) < 1.0) {
                setLegs(0, 0, SW_KNEE_BASE, SW_KNEE_BASE, 0, 0);
                usleep(10000);
            }
            printf(" done\n\n");
        }
    }

    centerAllServos();
    printf("\nSingle-leg test complete.\n");
}


// ============================================================
// SMOOTH PHASE WALK
// Uses smoothstep easing and sinArc bell curves for fluid motion.
// Run testSingleLegSmooth() first to verify SW_ANKLE_SHIFT is sufficient.
//
// 6-phase cycle (one full stride):
//   SHIFT_R : rAnkle shifts right (smoothstep), lAnkle bell push
//   SWING_L : support hip/knee advance COM; swing knee arc + hip forward
//   SETTLE1 : return support ankle/hip/knee to neutral
//   SHIFT_L : mirror
//   SWING_R : mirror
//   SETTLE2 : mirror
// ============================================================

void walkSmooth() {
    printf("=== SMOOTH WALK ===\n");
    printf("Shift=%.0fms  Swing=%.0fms  Settle=%.0fms\n",
        SW_SHIFT_MS, SW_SWING_MS, SW_SETTLE_MS);
    printf("AnkleShift=%.1f  AnklePush=%.1f  ComHip=%.1f  ComKnee=%.1f  "
        "SwingHip=%.1f  SwingKnee=%.1f\n\n",
        SW_ANKLE_SHIFT, SW_ANKLE_PUSH, SW_COM_HIP, SW_COM_KNEE,
        SW_SWING_HIP, SW_SWING_KNEE);

    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;
    imu.initialized = false;

    enum SwPhase { SHIFT_R = 0, SWING_L, SETTLE_1, SHIFT_L, SWING_R, SETTLE_2, SW_N_PHASES };
    const char* phaseNames[] = { "SHIFT_R","SWING_L","SETTLE1","SHIFT_L","SWING_R","SETTLE2" };
    const double phaseDurMs[] = { SW_SHIFT_MS, SW_SWING_MS, SW_SETTLE_MS,
                                   SW_SHIFT_MS, SW_SWING_MS, SW_SETTLE_MS };

    int    walkPhase = SHIFT_R;
    double phaseStart = getTimeSeconds();
    int    stepCount = 0;

    // Hip angles recorded when swing leg lands; SHIFT phases return them to neutral.
    double landedLHip = 0.0;
    double landedRHip = 0.0;

    double pitchIntegral = 0.0;
    double lastLoopTime = getTimeSeconds();

    while (balanceRunning) {
        double loopStart = getTimeSeconds();
        double dt = loopStart - lastLoopTime;
        lastLoopTime = loopStart;
        if (dt < 0.005 || dt > 0.1) dt = 0.01;
        double phaseElapsed = (loopStart - phaseStart) * 1000.0;  // ms
        double t = phaseElapsed / phaseDurMs[walkPhase];
        if (t > 1.0) t = 1.0;
        double st = smoothstep(t);

        imuUpdate();
        if (fabs(imu.pitch) > MAX_TILT_DEG || fabs(imu.roll) > MAX_TILT_DEG) {
            printf("EMERGENCY: tilt exceeded (pitch=%.1f roll=%.1f)\n",
                imu.pitch, imu.roll);
            break;
        }

        // Pitch PID correction.
        // I term accumulates persistent bias P+D cannot cancel (e.g. weight distribution).
        double pitchCorr = 0.0;
        {
            double predPitch = imu.pitch + imu.pitchRate * WALK_LOOK_AHEAD;
            double pitchErr = predPitch - COM_FORWARD_LEAN_DEG;
            pitchIntegral += pitchErr * dt;
            if (pitchIntegral > WALK_PITCH_KI_MAX) pitchIntegral = WALK_PITCH_KI_MAX;
            if (pitchIntegral < -WALK_PITCH_KI_MAX) pitchIntegral = -WALK_PITCH_KI_MAX;
            if (fabs(pitchErr) > WALK_DEADBAND) {
                double eff = pitchErr > 0 ? pitchErr - WALK_DEADBAND : pitchErr + WALK_DEADBAND;
                pitchCorr = -(WALK_PITCH_KP * eff
                    + WALK_PITCH_KI * pitchIntegral
                    + WALK_PITCH_KD * imu.pitchRate);
                if (pitchCorr > WALK_HIP_LIMIT) pitchCorr = WALK_HIP_LIMIT;
                if (pitchCorr < -WALK_HIP_LIMIT) pitchCorr = -WALK_HIP_LIMIT;
            }
        }

        double rHip = 0, lHip = 0;
        double rKnee = SW_KNEE_BASE, lKnee = SW_KNEE_BASE;
        double rAnkle = 0, lAnkle = 0;

        switch (walkPhase) {

        case SHIFT_R:
            // Shift weight to right foot. Push ankle ramps to full and STAYS (like testSingleLegSmooth).
            // sinArc (returns to 0) caused instability: robot fell when push disappeared before swing.
            rAnkle = -SW_ANKLE_SHIFT * st;
            lAnkle = -SW_ANKLE_PUSH * st;        // linear ramp — holds at full until SWING_L returns it
            rHip = landedRHip;
            lHip = 0;
            break;

        case SWING_L:
            // Swing left foot forward. Push ankle returns to 0 here (foot is in the air — safe to move).
            rAnkle = -SW_ANKLE_SHIFT;
            lAnkle = -SW_ANKLE_PUSH * (1.0 - st);  // return push ankle to flat as leg swings
            rHip = landedRHip * (1.0 - st);
            lKnee = SW_KNEE_BASE + SW_SWING_KNEE * sinArc(t);
            lHip = SW_SWING_HIP * st;
            break;

        case SETTLE_1:
            rAnkle = -SW_ANKLE_SHIFT * (1.0 - st);
            rHip = 0;              // fully returned during SWING_L
            lHip = landedLHip;    // hold left at landed angle
            break;

        case SHIFT_L:
            // Mirror of SHIFT_R: push ankle ramps to full and holds until SWING_R returns it.
            lAnkle = +SW_ANKLE_SHIFT_L * st;        // reduced left support (left ankle ~2x more effective)
            rAnkle = +SW_ANKLE_PUSH * st;
            lHip = landedLHip;
            rHip = 0;
            break;

        case SWING_R:
            // Swing right foot forward. Push ankle returns to 0 here (foot in the air).
            lAnkle = +SW_ANKLE_SHIFT_L;             // hold reduced left support
            rAnkle = +SW_ANKLE_PUSH * (1.0 - st);
            lHip = landedLHip * (1.0 - st);
            rKnee = SW_KNEE_BASE + SW_SWING_KNEE_R * sinArc(t);  // extra lift: HIP_R_TRIM makes right arc larger
            rHip = SW_SWING_HIP * st;
            break;

        case SETTLE_2:
            lAnkle = +SW_ANKLE_SHIFT_L * (1.0 - st);  // return from reduced left support
            lHip = 0;
            rHip = landedRHip;
            break;
        }

        // Roll correction during SETTLE phases: both feet planted, ankle differential is safe.
        // Both ankles += rollCorr shifts COM laterally (positive = COM left, corrects rightward lean).
        double rollCorr = 0.0;
        if (walkPhase == SETTLE_1 || walkPhase == SETTLE_2) {
            rollCorr = fmax(-8.0, fmin(8.0, WALK_ROLL_KP * imu.roll));
            rAnkle += rollCorr;
            lAnkle += rollCorr;
        }

        // Apply correction to support hip only during swing phases.
        // Applying it to the swing hip amplifies forward pitch (swing leg is already moving forward).
        setLegs(rHip + (walkPhase == SWING_R ? 0.0 : pitchCorr),
            lHip + (walkPhase == SWING_L ? 0.0 : pitchCorr),
            rKnee, lKnee, rAnkle, lAnkle);

        if (t >= 1.0) {
            if (walkPhase == SWING_L) { landedLHip = SW_SWING_HIP; landedRHip = 0; }
            if (walkPhase == SWING_R) { landedRHip = SW_SWING_HIP; landedLHip = 0; }
            double cmdRHip = rHip + (walkPhase == SWING_R ? 0.0 : pitchCorr);
            double cmdLHip = lHip + (walkPhase == SWING_L ? 0.0 : pitchCorr);
            printf("  %-8s t=%.0fms | rH=%+5.1f lH=%+5.1f rK=%+5.1f lK=%+5.1f rA=%+5.1f lA=%+5.1f | pCorr=%+5.1f p=%+5.1f roll=%+5.1f\n",
                phaseNames[walkPhase], phaseElapsed,
                cmdRHip, cmdLHip, rKnee, lKnee, rAnkle, lAnkle,
                pitchCorr, imu.pitch, imu.roll);
            walkPhase = (walkPhase + 1) % SW_N_PHASES;
            phaseStart = loopStart;
            if (walkPhase == SHIFT_R) printf("--- Step %d ---\n", ++stepCount);
        }

        usleep(10000);  // 100 Hz
    }

    centerAllServos();
    printf("walkSmooth stopped after %d steps.\n", stepCount);
}


// ============================================================
// MY WALK SMOOTH — smooth version of myWalk()
// 4-phase push-off gait with 100 Hz loop and IMU pitch PID.
//
// Key insight: SHIFT and hip-RETURN happen simultaneously.
// While ankles lerp to the new support, the pushed hip de-extends
// with the foot lifted — this is the forward swing of that foot.
// The previous support ankle stays planted until weight fully transfers.
//
//   SHIFT_R: ankles lerp right-support + left-lift;
//            left hip/knee return from PUSH_L simultaneously
//   PUSH_R:  hold ankles; right hip extends, right knee compensates
//   SHIFT_L: ankles lerp left-support + right-lift;
//            right hip/knee return simultaneously (foot swings forward)
//   PUSH_L:  mirror of PUSH_R
// ============================================================
// turnBias > 0 → right side pushes harder → arcs LEFT.
// turnBias < 0 → left side pushes harder  → arcs RIGHT.
// maxSteps: stop after this many full strides (0 = unlimited, runs until Ctrl-C).
// Both hip and knee scale together to keep torso vertical during asymmetric push.
void myWalkSmoothTurn(double turnBias, int maxSteps = 0) {
    double rPush = fmax(0.0, MWS_HIP_PUSH + turnBias);  // right-side push magnitude
    double lPush = fmax(0.0, MWS_HIP_PUSH - turnBias);  // left-side push magnitude

    printf("=== MY WALK SMOOTH (turn=%.1f  maxSteps=%d) ===\n", turnBias, maxSteps);
    printf("Shift=%.0fms  Push=%.0fms  rPush=%.1f  lPush=%.1f\n",
        MWS_SHIFT_MS, MWS_PUSH_MS, rPush, lPush);

    enum MWSPhase { SHIFT_R = 0, PUSH_R, SHIFT_L, PUSH_L, MWS_N_PHASES };
    const char* phaseNames[] = { "SHIFT_R", "PUSH_R", "SHIFT_L", "PUSH_L" };
    const double phaseDurMs[] = { MWS_SHIFT_MS, MWS_PUSH_MS, MWS_SHIFT_MS, MWS_PUSH_MS };

    double pitchIntegral = 0.0;
    int    phase = SHIFT_R;
    double phaseStart = getTimeSeconds();
    int    stepCount = 0;

    double pRH = 0, pLH = 0, pRK = 0, pLK = 0, pRA = 0, pLA = 0;
    double rHip = 0, lHip = 0, rKnee = 0, lKnee = 0, rAnkle = 0, lAnkle = 0;

    imu.initialized = false;
    signal(SIGINT, balanceSignalHandler);
    balanceRunning = true;

    while (balanceRunning) {
        double loopStart = getTimeSeconds();
        imuUpdate();

        if (fabs(imu.pitch) > MAX_TILT_DEG || fabs(imu.roll) > MAX_TILT_DEG) {
            printf("EMERGENCY: pitch=%.1f roll=%.1f\n", imu.pitch, imu.roll);
            break;
        }

        double dt = 0.01;
        double phaseElapsed = (loopStart - phaseStart) * 1000.0;
        double t = fmin(1.0, phaseElapsed / phaseDurMs[phase]);
        double st = smoothstep(t);

        double pitchCorr = 0.0;
        {
            double pitchErr = imu.pitch - COM_FORWARD_LEAN_DEG;
            pitchIntegral += pitchErr * dt;
            if (pitchIntegral > WALK_PITCH_KI_MAX) pitchIntegral = WALK_PITCH_KI_MAX;
            if (pitchIntegral < -WALK_PITCH_KI_MAX) pitchIntegral = -WALK_PITCH_KI_MAX;
            if (fabs(pitchErr) > WALK_DEADBAND) {
                double eff = pitchErr > 0.0 ? pitchErr - WALK_DEADBAND : pitchErr + WALK_DEADBAND;
                pitchCorr = -(MWS_PITCH_KP * eff + WALK_PITCH_KI * pitchIntegral);
                if (pitchCorr > WALK_HIP_LIMIT) pitchCorr = WALK_HIP_LIMIT;
                if (pitchCorr < -WALK_HIP_LIMIT) pitchCorr = -WALK_HIP_LIMIT;
            }
        }

        rHip = 0; lHip = 0; rKnee = 0; lKnee = 0; rAnkle = 0; lAnkle = 0;

        switch (phase) {
        case SHIFT_R:
            rAnkle = pRA + (-MWS_ANKLE_TILT - pRA) * st;
            lAnkle = pLA + (-MWS_ANKLE_PUSH - pLA) * st;
            lHip = pLH * (1.0 - st);
            lKnee = pLK * (1.0 - st);
            break;
        case PUSH_R:
            rAnkle = -MWS_ANKLE_TILT;
            lAnkle = -MWS_ANKLE_PUSH;
            rHip = -rPush * st;   // right push (larger when turnBias > 0)
            rKnee = -rPush * st;   // knee scales with push to keep torso vertical
            break;
        case SHIFT_L:
            lAnkle = pLA + (+MWS_ANKLE_TILT - pLA) * st;
            rAnkle = pRA + (+MWS_ANKLE_PUSH - pRA) * st;
            rHip = pRH * (1.0 - st);
            rKnee = pRK * (1.0 - st);
            break;
        case PUSH_L:
            lAnkle = +MWS_ANKLE_TILT;
            rAnkle = +MWS_ANKLE_PUSH;
            lHip = -lPush * st;   // left push (smaller when turnBias > 0)
            lKnee = -lPush * st;
            break;
        }

        setLegs(rHip - pitchCorr, lHip - pitchCorr, rKnee, lKnee, rAnkle, lAnkle);

        if (t >= 1.0) {
            printf("  %-8s t=%.0fms | rH=%+5.1f lH=%+5.1f rK=%+5.1f lK=%+5.1f rA=%+5.1f lA=%+5.1f | pCorr=%+5.1f p=%+5.1f\n",
                phaseNames[phase], phaseElapsed,
                rHip - pitchCorr, lHip - pitchCorr, rKnee, lKnee, rAnkle, lAnkle,
                pitchCorr, imu.pitch);
            pRH = rHip; pLH = lHip; pRK = rKnee; pLK = lKnee; pRA = rAnkle; pLA = lAnkle;
            phase = (phase + 1) % MWS_N_PHASES;
            phaseStart = loopStart;
            if (phase == SHIFT_R) {
                ++stepCount;
                if (maxSteps > 0 && stepCount >= maxSteps)
                    balanceRunning = false;
                else
                    printf("--- Step %d ---\n", stepCount);
            }
        }

        usleep(10000);  // 100 Hz
    }

    // Smooth ramp back to neutral from whatever pose the last phase left.
    // Prevents the abrupt snap of centerAllServos() from destabilising the robot
    // between chained myWalkSmoothTurn() calls.
    {
        const double settleDurMs = 400.0;
        double settleStart = getTimeSeconds();
        while (true) {
            double elapsed = (getTimeSeconds() - settleStart) * 1000.0;
            double t = fmin(1.0, elapsed / settleDurMs);
            double st = smoothstep(t);
            setLegs(pRH * (1.0 - st), pLH * (1.0 - st),
                pRK * (1.0 - st), pLK * (1.0 - st),
                pRA * (1.0 - st), pLA * (1.0 - st));
            if (t >= 1.0) break;
            usleep(10000);
        }
        usleep(500000);  // 500ms hold at neutral before returning
    }
    centerAllServos();
    printf("myWalkSmoothTurn done: %d steps.\n", stepCount);
}

void myWalkSmooth() { myWalkSmoothTurn(0.0, 0); }
void myWalkSmooth2() { myWalkSmooth(); }


